### ISSUE TITLE
Superhosttools.com Down?

### ISSUE THREAD

**Issue by christianhartman** [wootwoot1234/Superhost-Tools#21]
Noticing error messages. 

Connect
500 MongoError: Topology was destroyed
   at nextFunction (/app/node_modules/mongodb-core/lib/cursor.js:540:25)
   at Cursor.next [as _next] (/app/node_modules/mongodb-core/lib/cursor.js:692:3)
   at nextObject (/app/node_modules/mongodb/lib/cursor.js:679:8)
   at Cursor.next (/app/node_modules/mongodb/lib/cursor.js:269:12)
   at Cursor.<anonymous> (/app/node_modules/newrelic/lib/shim/shim.js:883:19)
   at Cursor.next (/app/node_modules/newrelic/lib/shim/shim.js:883:19)
   at findOne (/app/node_modules/mongodb/lib/collection.js:1415:10)
   at Collection.findOne (/app/node_modules/mongodb/lib/collection.js:1401:44)
   at Collection.findOne (/app/node_modules/newrelic/lib/shim/shim.js:883:19)
   at Collection.tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
   at Collection.ret [as findOneAsync] (eval at makeNodePromisifiedEval (/app/node_modules/bluebird/js/release/promisify.js:1:1), <anonymous>:14:23)
   at collectionReady.then.collection (/app/node_modules/connect-mongo/src/index.js:195:48)
   at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:183:28)
   at Promise.linkTransaction (/app/node_modules/newrelic/lib/instrumentation/promise.js:297:65)
   at Promise.wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:183:28)
   at __NR_wrappedThenHandler (/app/node_modules/newrelic/lib/instrumentation/promise.js:473:26)
   at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
   at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
   at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
   at Promise._settlePromiseCtx (/app/node_modules/bluebird/js/release/promise.js:606:10)
   at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:138:12)
   at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)
   at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)

**Comment by wootwoot1234** [comment]
Thanks for letting me know.  It's back up now.
