### ISSUE TITLE
Not able to add account. 

### ISSUE THREAD

**Issue by shawnwong84** [wootwoot1234/Superhost-Tools#60]
Hello, I'm using heroku for this.

Any other settle i need to do? 
2018-06-05T16:23:08.363079+00:00 app[web.1]:   error_message: 'Unable to perform action. Please try again through the website or contact support if you need immediate assistance.',
2018-06-05T16:23:08.363081+00:00 app[web.1]:   client_error_info:
2018-06-05T16:23:08.363083+00:00 app[web.1]:    { airlock:
2018-06-05T16:23:08.363085+00:00 app[web.1]:       { action_name: 'account_login',
2018-06-05T16:23:08.363086+00:00 app[web.1]:         completion_redirect_url: '',
2018-06-05T16:23:08.363088+00:00 app[web.1]:         error_redirect_url: '',
2018-06-05T16:23:08.363089+00:00 app[web.1]:         escapable: true,
2018-06-05T16:23:08.363091+00:00 app[web.1]:         fallback_friction: 'contact_us_form',
2018-06-05T16:23:08.363092+00:00 app[web.1]:         first_name: 'Peter',
2018-06-05T16:23:08.363094+00:00 app[web.1]:         flow: 'captcha_flow',
2018-06-05T16:23:08.363095+00:00 app[web.1]:         friction_data: [Object],
2018-06-05T16:23:08.363097+00:00 app[web.1]:         header_text: 'Please verify yourself',
2018-06-05T16:23:08.363101+00:00 app[web.1]:         identifier: null,
2018-06-05T16:23:08.363102+00:00 app[web.1]:         keep_webview_open_on_redirect: false,
2018-06-05T16:23:08.363105+00:00 app[web.1]:         status: 0,
2018-06-05T16:23:08.363099+00:00 app[web.1]:         id: 1433474005,
2018-06-05T16:23:08.363107+00:00 app[web.1]:         should_replay_request: true,
2018-06-05T16:23:08.363104+00:00 app[web.1]:         redux: true,
2018-06-05T16:23:08.363108+00:00 app[web.1]:         user_id: 193679402,
2018-06-05T16:23:08.363112+00:00 app[web.1]:      metadata: {} } }
2018-06-05T16:23:08.363110+00:00 app[web.1]:         user_message: null },
2018-06-05T16:23:08.382464+00:00 app[web.1]: performAirbnbRequest() LOGIN FAILED
2018-06-05T16:23:08.382719+00:00 app[web.1]: Error: Unable to perform action. Please try again through the website or contact support if you need immediate assistance.
2018-06-05T16:23:08.382722+00:00 app[web.1]:     at /app/routes.js:688:28
2018-06-05T16:23:08.382724+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:109:7)
2018-06-05T16:23:08.382781+00:00 app[web.1]: ERROR: Unable to perform action. Please try again through the website or contact support if you need immediate assistance.
2018-06-05T16:23:08.382857+00:00 app[web.1]: ERROR MSG: /addAccount

**Comment by wootwoot1234** [comment]
It looks like the account is being flagged by airbnb and needs to be verified, the code here on github isn't able handle accounts that have been flagged by airbnb, I haven't released the updated code on superhosttools.com.  I recommend creating an account on superhosttools.com, it can handle accounts that have been flagged.
